### ISSUE TITLE
inline-r kernel restarting

### ISSUE THREAD

**Issue by bbernst** [vaibhavsagar/notebooks#1]
Hi, I'm having issues after entering the notebook where the kernel restarts when trying to run the second cell in the example notebook.

```
[I 12:42:17.128 NotebookApp] Adapting to protocol v5.0 for kernel accf02dc-e2b4-4132-b473-7e99b5567218
[I 12:42:22.740 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
kernel accf02dc-e2b4-4132-b473-7e99b5567218 restarted
```

Any ideas?

**Comment by bbernst** [comment]
I tried using the updated versions you list [here](https://github.com/vaibhavsagar/notebooks/blob/master/versions.json), but same issue

**Comment by vaibhavsagar** [comment]
I pushed a small change to use `ghc864` instead of `ghc865`, which shouldn't make any real difference, and it continues to work for me. Maybe try nuking your `~/.local/share/jupyter/` directory and running it again?

In any case, this is my personal notebooks repo, not a project for which there is any expectation of support, so I am closing this.
